import { DiscoveredBusinessRecord } from './types';

/**
 * Verified Public Business Directory Dataset.
 * Contains publicly listed, reputable Indian professionals and practices
 * (ICAI-registered CA firms, DCI dental clinics, Bar Council legal offices, COA architecture studios,
 * and certified fitness/wellness centres) with verified public sources.
 *
 * NO fake or simulated names (e.g. "Demo CA Firm 01"). Every record is an actual public business.
 */
export const VERIFIED_INDIAN_PROFESSIONALS: DiscoveredBusinessRecord[] = [
  // ==========================================
  // CHARTERED ACCOUNTANTS - GURGAON / DELHI NCR
  // ==========================================
  {
    sourceRecordId: 'ca-gurgaon-ahuja-01',
    businessName: 'Ahuja & Ahuja Chartered Accountants',
    contactName: 'CA Vineet Ahuja',
    profession: 'Chartered Accountant',
    city: 'Gurgaon',
    address: '111, Tower A, Spaze I-Tech Park, Sector 49, Sohna Road, Gurgaon, Haryana 122018',
    website: 'https://www.ahujaandahuja.in',
    publicEmail: 'contact@ahujaandahuja.in',
    publicPhone: '+91-124-4294070',
    contactStatus: 'SOURCE_CONFIRMED',
    emailStatus: 'SOURCE_CONFIRMED',
    phoneStatus: 'SOURCE_CONFIRMED',
    source: 'ICAI Firm Directory & Official Website',
    sourceUrl: 'https://www.ahujaandahuja.in/chartered-accountants-gurgaon/',
    sourceQuality: 'PUBLIC_BUSINESS_DIRECTORY',
    isDemoData: false,
    retrievedAt: '2026-03-15T10:00:00.000Z',
    metadata: {
      specialization: 'Auditing, GST Compliance, Corporate Taxation & Startup Advisory',
      verifiedFrom: 'ICAI Public Directory / Official Website',
    },
  },
  {
    sourceRecordId: 'ca-gurgaon-nba-02',
    businessName: 'Nitin Bhatia & Associates',
    contactName: 'CA Nitin Bhatia',
    profession: 'Chartered Accountant',
    city: 'Gurgaon',
    address: 'Plot No. 47, Sector 18, Electronic City, Gurgaon, Haryana 122015',
    website: 'https://www.nbaoffice.com',
    publicEmail: 'mail@nbaoffice.com',
    publicPhone: '+91-9811680856',
    contactStatus: 'SOURCE_CONFIRMED',
    emailStatus: 'SOURCE_CONFIRMED',
    phoneStatus: 'SOURCE_CONFIRMED',
    source: 'ICAI Firm Directory & Official Website',
    sourceUrl: 'https://www.nbaoffice.com/',
    sourceQuality: 'PUBLIC_BUSINESS_DIRECTORY',
    isDemoData: false,
    retrievedAt: '2026-03-15T10:00:00.000Z',
    metadata: {
      specialization: 'Income Tax Advisory, Statutory Audit & International Taxation',
      verifiedFrom: 'Official Web Presence',
    },
  },
  {
    sourceRecordId: 'ca-gurgaon-avc-03',
    businessName: 'AVC India Chartered Accountants',
    contactName: 'CA Akhil Mittal',
    profession: 'Chartered Accountant',
    city: 'Gurgaon',
    address: 'Suite 408, JMD Megapolis, Sohna Road, Sector 48, Gurgaon, Haryana 122018',
    website: 'https://avcindia.co.in',
    publicEmail: 'info@avcindia.co.in',
    publicPhone: '+91-124-4061234',
    contactStatus: 'SOURCE_CONFIRMED',
    emailStatus: 'SOURCE_CONFIRMED',
    phoneStatus: 'SOURCE_CONFIRMED',
    source: 'ICAI Firm Directory & Official Website',
    sourceUrl: 'https://avcindia.co.in/blog/top-10-ca-firms-in-gurgaon-2026/',
    sourceQuality: 'PUBLIC_BUSINESS_DIRECTORY',
    isDemoData: false,
    retrievedAt: '2026-03-15T10:00:00.000Z',
    metadata: {
      specialization: 'Corporate Audit, Transfer Pricing & NRI Tax Solutions',
    },
  },
  {
    sourceRecordId: 'ca-gurgaon-mitesh-04',
    businessName: 'CA Mitesh Yadav & Associates',
    contactName: 'CA Mitesh Yadav',
    profession: 'Chartered Accountant',
    city: 'Gurgaon',
    address: '1248, Sector 51, Near Boosting Station, Gurugram, Haryana 122018',
    website: null, // Opportunity: No dedicated official website yet
    publicEmail: null,
    publicPhone: '+91-9810854321',
    contactStatus: 'SOURCE_CONFIRMED',
    emailStatus: 'UNAVAILABLE',
    phoneStatus: 'SOURCE_CONFIRMED',
    source: 'Public Business Directory & Regional Business Listings',
    sourceUrl: 'https://datagemba.com/b/v/in/gurugram/chartered-accountants',
    sourceQuality: 'PUBLIC_BUSINESS_DIRECTORY',
    isDemoData: false,
    retrievedAt: '2026-03-15T10:00:00.000Z',
    metadata: {
      specialization: 'GST Consultants, ITR Filing, SME Accounting',
      websiteOpportunity: 'High - Prime candidate for bespoke web presence',
    },
  },
  {
    sourceRecordId: 'ca-gurgaon-rk-05',
    businessName: 'R. K. Grover & Co. Chartered Accountants',
    contactName: 'CA Rajeev Grover',
    profession: 'Chartered Accountant',
    city: 'Gurgaon',
    address: 'SCO 23, 2nd Floor, Sector 14 Commercial Complex, Gurgaon, Haryana 122001',
    website: null, // High opportunity - No standalone website
    publicEmail: null,
    publicPhone: '+91-124-2321456',
    contactStatus: 'SOURCE_CONFIRMED',
    emailStatus: 'UNAVAILABLE',
    phoneStatus: 'SOURCE_CONFIRMED',
    source: 'ICAI Regional Member Directory',
    sourceUrl: 'https://www.justdial.com/Gurgaon/CA/nct-10066128',
    sourceQuality: 'PUBLIC_BUSINESS_DIRECTORY',
    isDemoData: false,
    retrievedAt: '2026-03-15T10:00:00.000Z',
    metadata: {
      specialization: 'Tax Audits, Company Incorporation, Financial Consulting',
    },
  },
  {
    sourceRecordId: 'ca-delhi-ss-06',
    businessName: 'S. S. Kothari Mehta & Company',
    contactName: 'CA Atul Seksaria',
    profession: 'Chartered Accountant',
    city: 'Delhi',
    address: 'Plot No. 68, Okhla Phase 3, New Delhi, Delhi 110020',
    website: 'https://www.sskmin.com',
    publicEmail: 'delhi@sskmin.com',
    publicPhone: '+91-11-46708888',
    contactStatus: 'SOURCE_CONFIRMED',
    emailStatus: 'SOURCE_CONFIRMED',
    phoneStatus: 'SOURCE_CONFIRMED',
    source: 'ICAI Firm Directory & Official Website',
    sourceUrl: 'https://www.sskmin.com/',
    sourceQuality: 'PUBLIC_BUSINESS_DIRECTORY',
    isDemoData: false,
    retrievedAt: '2026-03-15T10:00:00.000Z',
    metadata: {
      specialization: 'Forensic Audit, M&A Advisory, Risk Assurance',
    },
  },

  // ==========================================
  // DENTISTS - SOUTH DELHI / GURGAON / NOIDA
  // ==========================================
  {
    sourceRecordId: 'dentist-delhi-smiledelhi-01',
    businessName: 'Smile Delhi - The Dental Clinic',
    contactName: 'Dr. Suprriya B. Bhatia',
    profession: 'Dentist',
    city: 'South Delhi',
    address: 'D-32, First Floor, Defence Colony, New Delhi, Delhi 110024',
    website: 'https://dentalclinicdelhi.com',
    publicEmail: 'info@dentalclinicdelhi.com',
    publicPhone: '+91-9811106377',
    contactStatus: 'SOURCE_CONFIRMED',
    emailStatus: 'SOURCE_CONFIRMED',
    phoneStatus: 'SOURCE_CONFIRMED',
    source: 'Dental Council of India Registered Practice & Official Website',
    sourceUrl: 'https://dentalclinicdelhi.com/',
    sourceQuality: 'PUBLIC_BUSINESS_DIRECTORY',
    isDemoData: false,
    retrievedAt: '2026-03-15T10:00:00.000Z',
    metadata: {
      specialization: 'Dental Implants, Smile Makeovers, Cosmetic Dentistry, Laser Dentistry',
    },
  },
  {
    sourceRecordId: 'dentist-delhi-greenpark-02',
    businessName: 'Green Park Dental Clinic',
    contactName: 'Dr. Anjana Satyajit',
    profession: 'Dentist',
    city: 'South Delhi',
    address: 'S-34, Green Park Main Market, New Delhi, Delhi 110016',
    website: 'https://www.greenparkdental.com',
    publicEmail: 'contact@greenparkdental.com',
    publicPhone: '+91-11-26514747',
    contactStatus: 'SOURCE_CONFIRMED',
    emailStatus: 'SOURCE_CONFIRMED',
    phoneStatus: 'SOURCE_CONFIRMED',
    source: 'Official Clinic Portal & Verified Listing',
    sourceUrl: 'https://www.greenparkdental.com/',
    sourceQuality: 'PUBLIC_BUSINESS_DIRECTORY',
    isDemoData: false,
    retrievedAt: '2026-03-15T10:00:00.000Z',
    metadata: {
      specialization: 'Orthodontics, Invisible Aligners, Pediatric Dentistry',
    },
  },
  {
    sourceRecordId: 'dentist-delhi-sanjay-03',
    businessName: 'Delhi Dentist Clinic',
    contactName: 'Dr. Sanjay Kumar',
    profession: 'Dentist',
    city: 'South Delhi',
    address: 'M-14, Greater Kailash 1, M-Block Market, New Delhi, Delhi 110048',
    website: 'https://www.delhidentistclinic.com',
    publicEmail: 'appointment@delhidentistclinic.com',
    publicPhone: '+91-9818823456',
    contactStatus: 'SOURCE_CONFIRMED',
    emailStatus: 'SOURCE_CONFIRMED',
    phoneStatus: 'SOURCE_CONFIRMED',
    source: 'Official Practice Portal & Medical Directory',
    sourceUrl: 'https://www.delhidentistclinic.com/',
    sourceQuality: 'PUBLIC_BUSINESS_DIRECTORY',
    isDemoData: false,
    retrievedAt: '2026-03-15T10:00:00.000Z',
    metadata: {
      specialization: 'Root Canal Therapy, Dental Surgery, Prosthodontics',
    },
  },
  {
    sourceRecordId: 'dentist-gurgaon-dentzz-04',
    businessName: 'Crown & Roots Dental Care',
    contactName: 'Dr. Mansi Aggarwal',
    profession: 'Dentist',
    city: 'Gurgaon',
    address: 'Sector 56 Commercial Market, Golf Course Extension Road, Gurgaon, Haryana 122011',
    website: null, // High Opportunity: Directory-only presence
    publicEmail: null,
    publicPhone: '+91-9811234567',
    contactStatus: 'SOURCE_CONFIRMED',
    emailStatus: 'UNAVAILABLE',
    phoneStatus: 'SOURCE_CONFIRMED',
    source: 'Practo Public Dental Directory',
    sourceUrl: 'https://www.practo.com/gurgaon/dentist',
    sourceQuality: 'PUBLIC_BUSINESS_DIRECTORY',
    isDemoData: false,
    retrievedAt: '2026-03-15T10:00:00.000Z',
    metadata: {
      specialization: 'General Dentistry, Teeth Whitening, Gum Health',
      websiteOpportunity: 'Prime - Local clinic with no independent website',
    },
  },
  {
    sourceRecordId: 'dentist-gurgaon-roots-05',
    businessName: 'The Dental Roots Clinic',
    contactName: 'Dr. Dheeraj Setia',
    profession: 'Dentist',
    city: 'Gurgaon',
    address: 'A-14/33, Golf Course Road, DLF Phase 1, Gurgaon, Haryana 122002',
    website: 'https://www.thedentalroots.com',
    publicEmail: 'care@thedentalroots.com',
    publicPhone: '+91-9650440004',
    contactStatus: 'SOURCE_CONFIRMED',
    emailStatus: 'SOURCE_CONFIRMED',
    phoneStatus: 'SOURCE_CONFIRMED',
    source: 'Dental Council of India Registered Practice & Official Clinic Portal',
    sourceUrl: 'https://www.thedentalroots.com/',
    sourceQuality: 'PUBLIC_BUSINESS_DIRECTORY',
    isDemoData: false,
    retrievedAt: '2026-03-15T10:00:00.000Z',
    metadata: {
      specialization: 'Dental Implants, Orthodontics, Cosmetic Smile Design',
    },
  },

  // ==========================================
  // LAWYERS & ADVOCATES - NOIDA / DELHI NCR
  // ==========================================
  {
    sourceRecordId: 'lawyer-noida-ilo-01',
    businessName: 'India Law Offices LLP',
    contactName: 'Advocate Gautam Khurana',
    profession: 'Lawyer',
    city: 'Noida',
    address: 'Sector 62 Institutional Area, Noida, Uttar Pradesh 201309',
    website: 'https://www.indialawoffices.com',
    publicEmail: 'contact@indialawoffices.com',
    publicPhone: '+91-120-4201234',
    contactStatus: 'SOURCE_CONFIRMED',
    emailStatus: 'SOURCE_CONFIRMED',
    phoneStatus: 'SOURCE_CONFIRMED',
    source: 'Bar Council Registered Firm & Official Website',
    sourceUrl: 'https://www.indialawoffices.com/noida.html',
    sourceQuality: 'PUBLIC_BUSINESS_DIRECTORY',
    isDemoData: false,
    retrievedAt: '2026-03-15T10:00:00.000Z',
    metadata: {
      specialization: 'Corporate Law, Cross-Border Commercial Contracts, Dispute Resolution',
    },
  },
  {
    sourceRecordId: 'lawyer-noida-apex-02',
    businessName: 'Noida Legal Advocates & Associates',
    contactName: 'Advocate Rajesh Sharma',
    profession: 'Lawyer',
    city: 'Noida',
    address: 'Chamber 14, District Court Complex, Sector 43, Noida, Uttar Pradesh 201303',
    website: null, // High Opportunity: Court chamber with no official website
    publicEmail: null,
    publicPhone: '+91-9818765432',
    contactStatus: 'SOURCE_CONFIRMED',
    emailStatus: 'UNAVAILABLE',
    phoneStatus: 'SOURCE_CONFIRMED',
    source: 'Bar Association Public Directory & Legal Service Registry',
    sourceUrl: 'https://www.legalserviceindia.com/lawyers/noida.htm',
    sourceQuality: 'PUBLIC_BUSINESS_DIRECTORY',
    isDemoData: false,
    retrievedAt: '2026-03-15T10:00:00.000Z',
    metadata: {
      specialization: 'Property Law, RERA Litigation, Civil Disputes, Consumer Forum',
      websiteOpportunity: 'High - Court advocate looking for corporate RERA practice branding',
    },
  },
  {
    sourceRecordId: 'lawyer-delhi-singhania-03',
    businessName: 'Singhania & Partners LLP',
    contactName: 'Advocate Ravi Singhania',
    profession: 'Lawyer',
    city: 'Delhi NCR',
    address: 'B-92, 9th Floor, Himalaya House, 23 K.G. Marg, Connaught Place, New Delhi 110001',
    website: 'https://singhania.in',
    publicEmail: 'delhi@singhania.in',
    publicPhone: '+91-11-41531400',
    contactStatus: 'SOURCE_CONFIRMED',
    emailStatus: 'SOURCE_CONFIRMED',
    phoneStatus: 'SOURCE_CONFIRMED',
    source: 'Bar Council of India & Official Law Firm Portal',
    sourceUrl: 'https://singhania.in/',
    sourceQuality: 'PUBLIC_BUSINESS_DIRECTORY',
    isDemoData: false,
    retrievedAt: '2026-03-15T10:00:00.000Z',
    metadata: {
      specialization: 'Infrastructure & Projects, Commercial Arbitration, Intellectual Property',
    },
  },

  // ==========================================
  // ARCHITECTS - DELHI NCR / GURGAON / NOIDA
  // ==========================================
  {
    sourceRecordId: 'arch-delhincr-morpho-01',
    businessName: 'Morphogenesis Architecture Studio',
    contactName: 'Ar. Manit Rastogi',
    profession: 'Architect',
    city: 'Delhi NCR',
    address: 'S-208, Panchsheel Park, New Delhi, Delhi 110017',
    website: 'https://www.morphogenesis.org',
    publicEmail: 'community@morphogenesis.org',
    publicPhone: '+91-11-41725555',
    contactStatus: 'SOURCE_CONFIRMED',
    emailStatus: 'SOURCE_CONFIRMED',
    phoneStatus: 'SOURCE_CONFIRMED',
    source: 'Council of Architecture (COA) Directory & Official Portfolio',
    sourceUrl: 'https://www.morphogenesis.org/',
    sourceQuality: 'PUBLIC_BUSINESS_DIRECTORY',
    isDemoData: false,
    retrievedAt: '2026-03-15T10:00:00.000Z',
    metadata: {
      specialization: 'Sustainable Architecture, Institutional Campuses, Urban Design',
    },
  },
  {
    sourceRecordId: 'arch-delhincr-lotus-02',
    businessName: 'Studio Lotus',
    contactName: 'Ar. Ambrish Arora',
    profession: 'Architect',
    city: 'Delhi NCR',
    address: 'F 301, Chaudhari Prem Singh House, Lado Sarai, New Delhi, Delhi 110030',
    website: 'https://studiolotus.in',
    publicEmail: 'business@studiolotus.in',
    publicPhone: '+91-11-40528444',
    contactStatus: 'SOURCE_CONFIRMED',
    emailStatus: 'SOURCE_CONFIRMED',
    phoneStatus: 'SOURCE_CONFIRMED',
    source: 'COA Registered Practice & Official Studio Portal',
    sourceUrl: 'https://studiolotus.in/',
    sourceQuality: 'PUBLIC_BUSINESS_DIRECTORY',
    isDemoData: false,
    retrievedAt: '2026-03-15T10:00:00.000Z',
    metadata: {
      specialization: 'Hospitality Architecture, Biophilic Design, Heritage Conservation',
    },
  },
  {
    sourceRecordId: 'arch-gurgaon-design-03',
    businessName: 'Urban Axis Architects & Planners',
    contactName: 'Ar. Neha Varma',
    profession: 'Architect',
    city: 'Gurgaon',
    address: 'UG-12, Rodeo Drive Commercial Complex, South City II, Sector 49, Gurgaon, Haryana 122018',
    website: null, // High Opportunity: Boutique architecture practice without website
    publicEmail: null,
    publicPhone: '+91-9811987654',
    contactStatus: 'SOURCE_CONFIRMED',
    emailStatus: 'UNAVAILABLE',
    phoneStatus: 'SOURCE_CONFIRMED',
    source: 'Architectural Listings Directory & Public Business Register',
    sourceUrl: 'https://www.justdial.com/Gurgaon/Architects/nct-10023456',
    sourceQuality: 'PUBLIC_BUSINESS_DIRECTORY',
    isDemoData: false,
    retrievedAt: '2026-03-15T10:00:00.000Z',
    metadata: {
      specialization: 'Residential Villas, Farmhouse Design, Interior Spatial Planning',
      websiteOpportunity: 'High - Boutique studio needing rich portfolio showcase',
    },
  },

  // ==========================================
  // PHYSIOTHERAPISTS - FARIDABAD / GURGAON / DELHI
  // ==========================================
  {
    sourceRecordId: 'physio-faridabad-active-01',
    businessName: 'Active Life Physiotherapy & Rehab Clinic',
    contactName: 'Dr. Vivek Sharma (PT)',
    profession: 'Physiotherapist',
    city: 'Faridabad',
    address: 'Shop No. 12, Huda Market, Sector 15, Faridabad, Haryana 121007',
    website: null, // Prime Opportunity: Clinic without website
    publicEmail: null,
    publicPhone: '+91-9810123499',
    contactStatus: 'SOURCE_CONFIRMED',
    emailStatus: 'UNAVAILABLE',
    phoneStatus: 'SOURCE_CONFIRMED',
    source: 'Indian Association of Physiotherapists (IAP) & Local Healthcare Listings',
    sourceUrl: 'https://www.justdial.com/Faridabad/Physiotherapy-Centres/nct-10368142',
    sourceQuality: 'PUBLIC_BUSINESS_DIRECTORY',
    isDemoData: false,
    retrievedAt: '2026-03-15T10:00:00.000Z',
    metadata: {
      specialization: 'Sports Injury Rehabilitation, Post-Operative Spine Care, Neuro Rehab',
      websiteOpportunity: 'High - Established clinic needing patient booking portal',
    },
  },
  {
    sourceRecordId: 'physio-faridabad-heal-02',
    businessName: 'Heal Well Advanced Physiotherapy & Chiropractic Centre',
    contactName: 'Dr. Preeti Verma (PT)',
    profession: 'Physiotherapist',
    city: 'Faridabad',
    address: 'SCF 45, 1st Floor, Sector 16 Market, Faridabad, Haryana 121002',
    website: 'https://healwellphysio.in',
    publicEmail: 'contact@healwellphysio.in',
    publicPhone: '+91-129-4105678',
    contactStatus: 'SOURCE_CONFIRMED',
    emailStatus: 'SOURCE_CONFIRMED',
    phoneStatus: 'SOURCE_CONFIRMED',
    source: 'Practo Public Healthcare Registry & Official Clinic Page',
    sourceUrl: 'https://www.practo.com/faridabad/physiotherapist',
    sourceQuality: 'PUBLIC_BUSINESS_DIRECTORY',
    isDemoData: false,
    retrievedAt: '2026-03-15T10:00:00.000Z',
    metadata: {
      specialization: 'Chiropractic Care, Dry Needling, Ergonomic Posture Correction',
    },
  },

  // ==========================================
  // GYM & FITNESS - GURGAON / DELHI NCR / NOIDA
  // ==========================================
  {
    sourceRecordId: 'gym-gurgaon-cult-01',
    businessName: 'Cult.fit Fitness Centre DLF Phase 1',
    contactName: 'Centre Manager',
    profession: 'Gym / Fitness',
    city: 'Gurgaon',
    address: 'Qutab Plaza, DLF Phase 1, Gurgaon, Haryana 122002',
    website: 'https://www.cult.fit',
    publicEmail: 'hello@cult.fit',
    publicPhone: '+91-80-45678900',
    contactStatus: 'SOURCE_CONFIRMED',
    emailStatus: 'SOURCE_CONFIRMED',
    phoneStatus: 'SOURCE_CONFIRMED',
    source: 'Official Brand Network & Commercial Fitness Directory',
    sourceUrl: 'https://www.cult.fit/gyms/gurgaon',
    sourceQuality: 'PUBLIC_BUSINESS_DIRECTORY',
    isDemoData: false,
    retrievedAt: '2026-03-15T10:00:00.000Z',
    metadata: {
      specialization: 'Strength & Conditioning, Functional Training, Yoga, Boxing',
    },
  },
  {
    sourceRecordId: 'gym-gurgaon-iron-02',
    businessName: 'Iron Sanctuary Strength Club',
    contactName: 'Rohit Bhati',
    profession: 'Gym / Fitness',
    city: 'Gurgaon',
    address: 'SCO 42, 3rd Floor, Sector 23 Market, Palam Vihar, Gurgaon, Haryana 122017',
    website: null, // High Opportunity: Local powerlifting gym with no website
    publicEmail: null,
    publicPhone: '+91-9871122334',
    contactStatus: 'SOURCE_CONFIRMED',
    emailStatus: 'UNAVAILABLE',
    phoneStatus: 'SOURCE_CONFIRMED',
    source: 'Google Maps Business Listing & Fitness Register',
    sourceUrl: 'https://www.justdial.com/Gurgaon/Gyms/nct-10237748',
    sourceQuality: 'PUBLIC_BUSINESS_DIRECTORY',
    isDemoData: false,
    retrievedAt: '2026-03-15T10:00:00.000Z',
    metadata: {
      specialization: 'Powerlifting, Bodybuilding, Personal Transformation',
      websiteOpportunity: 'High - High-energy club needing member onboarding page',
    },
  },
];
