import { LeadData, JobData, ConsentRecordData, SuppressionRecordData, AuditLogData } from '@/types';

export const DEMO_ORGANIZATION_ID = 'org-demo-gurgaon';

export function isExplicitDemoMode(): boolean {
  if (process.env.DEMO_MODE !== undefined) {
    return process.env.DEMO_MODE === 'true';
  }
  if (process.env.NEXT_PUBLIC_DEMO_MODE !== undefined) {
    return process.env.NEXT_PUBLIC_DEMO_MODE === 'true';
  }
  return true;
}


export const INITIAL_DEMO_LEADS: LeadData[] = [
  {
    id: 'demo-lead-001',
    businessName: 'Demo CA Firm 01',
    profession: 'Chartered Accountant',
    city: 'Gurgaon',
    address: 'Demo Tower 1, DLF Cyber City, Phase 2, Gurgaon, Haryana 122002',
    website: 'https://demo-ca-01.example',
    publicEmail: 'contact@demo-ca-01.example',
    publicPhone: '+91-124-5550101',
    source: 'Public ICAI Directory (Fictional Demo Entry)',
    sourceUrl: 'https://directory.example/demo-ca-01',
    websiteStatus: 'WEBSITE_EXISTS',
    leadStatus: 'QUALIFIED',
    opportunityScore: 88,
    opportunityReason: '12-year-old static HTML website without mobile responsiveness or SSL certificate. High potential for corporate tax portal demo.',
    isDemoData: true,
    organizationId: DEMO_ORGANIZATION_ID,
    createdAt: new Date(Date.now() - 1000 * 60 * 60 * 24 * 7).toISOString(),
    updatedAt: new Date(Date.now() - 1000 * 60 * 60 * 4).toISOString(),
    contacts: [
      {
        id: 'contact-001',
        name: 'Demo Partner A',
        role: 'Senior Partner',
        email: 'partner.a@demo-ca-01.example',
        phone: '+91-981-5550101',
        isPrimary: true,
        linkedinUrl: 'https://linkedin.example/in/demo-partner-a',
        leadId: 'demo-lead-001',
        organizationId: DEMO_ORGANIZATION_ID,
        createdAt: new Date(Date.now() - 1000 * 60 * 60 * 24 * 7).toISOString(),
        updatedAt: new Date().toISOString(),
      },
    ],
    websites: [
      {
        id: 'web-001',
        url: 'https://demo-ca-01.example',
        status: 'WEBSITE_EXISTS',
        cms: 'Static HTML4',
        speedScore: 34,
        mobileFriendly: false,
        hasSsl: false,
        auditNotes: 'Missing SSL certificate, broken links on careers page, no client document vault.',
        leadId: 'demo-lead-001',
        organizationId: DEMO_ORGANIZATION_ID,
        createdAt: new Date().toISOString(),
        updatedAt: new Date().toISOString(),
      },
    ],
    activities: [
      {
        id: 'act-001',
        type: 'DISCOVERY',
        title: 'Lead Discovered',
        description: 'Discovered via public business directory scan (Demo Seed).',
        leadId: 'demo-lead-001',
        userId: 'demo-user-admin',
        organizationId: DEMO_ORGANIZATION_ID,
        createdAt: new Date(Date.now() - 1000 * 60 * 60 * 24 * 7).toISOString(),
      },
      {
        id: 'act-002',
        type: 'AUDIT',
        title: 'Website Audited',
        description: 'Website audit flagged missing mobile viewport and HTTP-only protocol.',
        leadId: 'demo-lead-001',
        userId: 'demo-user-admin',
        organizationId: DEMO_ORGANIZATION_ID,
        createdAt: new Date(Date.now() - 1000 * 60 * 60 * 24 * 5).toISOString(),
      },
      {
        id: 'act-003',
        type: 'STATUS_CHANGE',
        title: 'Status Updated to QUALIFIED',
        description: 'Assigned 88 opportunity score based on non-compliant online presence.',
        leadId: 'demo-lead-001',
        userId: 'demo-user-admin',
        organizationId: DEMO_ORGANIZATION_ID,
        createdAt: new Date(Date.now() - 1000 * 60 * 60 * 4).toISOString(),
      },
    ],
  },
  {
    id: 'demo-lead-002',
    businessName: 'Demo Chartered Accountants',
    profession: 'Chartered Accountant',
    city: 'Gurgaon',
    address: 'Example Plaza, Golf Course Road, Sector 54, Gurgaon, Haryana 122003',
    website: 'https://demo-chartered-accts.example',
    publicEmail: 'info@demo-chartered-accts.example',
    publicPhone: '+91-124-5550102',
    source: 'Public Trade Register (Demo Record)',
    sourceUrl: 'https://directory.example/demo-chartered-accts',
    websiteStatus: 'WEBSITE_EXISTS',
    leadStatus: 'DEMO_GENERATED',
    opportunityScore: 92,
    opportunityReason: 'Expired SSL certificate triggering browser security warnings for prospective corporate clients in Golf Course Road tech corridor.',
    isDemoData: true,
    organizationId: DEMO_ORGANIZATION_ID,
    createdAt: new Date(Date.now() - 1000 * 60 * 60 * 24 * 6).toISOString(),
    updatedAt: new Date(Date.now() - 1000 * 60 * 60 * 12).toISOString(),
    contacts: [
      {
        id: 'contact-002',
        name: 'Demo Partner B',
        role: 'Managing Partner',
        email: 'partner.b@demo-chartered-accts.example',
        phone: '+91-981-5550102',
        isPrimary: true,
        leadId: 'demo-lead-002',
        organizationId: DEMO_ORGANIZATION_ID,
        createdAt: new Date().toISOString(),
        updatedAt: new Date().toISOString(),
      },
    ],
  },
  {
    id: 'demo-lead-003',
    businessName: 'Example Accounting Services',
    profession: 'Chartered Accountant',
    city: 'Gurgaon',
    address: 'Sector 44 Institutional Area, Gurgaon, Haryana 122003',
    website: null,
    publicEmail: 'inquiries@example-accounting.example',
    publicPhone: '+91-124-5550103',
    source: 'Registrar of Companies Listing (Demo)',
    sourceUrl: 'https://directory.example/example-accounting',
    websiteStatus: 'NO_WEBSITE',
    leadStatus: 'NEW',
    opportunityScore: 95,
    opportunityReason: 'Well-established 15-person firm handling GST and Transfer Pricing with zero online website footprint.',
    isDemoData: true,
    organizationId: DEMO_ORGANIZATION_ID,
    createdAt: new Date(Date.now() - 1000 * 60 * 60 * 24 * 2).toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: 'demo-lead-004',
    businessName: 'Mock Tax & Audit Associates',
    profession: 'Chartered Accountant',
    city: 'Delhi NCR',
    address: 'Barakhamba Road, Connaught Place, New Delhi 110001',
    website: 'https://mock-tax-audit.example',
    publicEmail: 'office@mock-tax-audit.example',
    publicPhone: '+91-11-5550104',
    source: 'Public Business Directory (Demo)',
    sourceUrl: 'https://directory.example/mock-tax-audit',
    websiteStatus: 'WEBSITE_EXISTS',
    leadStatus: 'OUTREACH_PENDING',
    opportunityScore: 78,
    opportunityReason: 'Desktop-only table-based layout that breaks on iOS and Android devices.',
    isDemoData: true,
    organizationId: DEMO_ORGANIZATION_ID,
    createdAt: new Date(Date.now() - 1000 * 60 * 60 * 24 * 5).toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: 'demo-lead-005',
    businessName: 'Fictional Financial Advisors CA',
    profession: 'Chartered Accountant',
    city: 'Gurgaon',
    address: 'Udyog Vihar Phase 4, Gurgaon, Haryana 122015',
    website: 'https://fictional-financial.example',
    publicEmail: 'admin@fictional-financial.example',
    publicPhone: '+91-124-5550105',
    source: 'Public Yellow Pages (Demo)',
    sourceUrl: 'https://directory.example/fictional-financial',
    websiteStatus: 'WEBSITE_EXISTS',
    leadStatus: 'CONTACTED',
    opportunityScore: 70,
    opportunityReason: 'Outdated copyright date (2016) and deprecated Flash animations.',
    isDemoData: true,
    organizationId: DEMO_ORGANIZATION_ID,
    createdAt: new Date(Date.now() - 1000 * 60 * 60 * 24 * 8).toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: 'demo-lead-006',
    businessName: 'Sample Chartered Partners',
    profession: 'Chartered Accountant',
    city: 'Gurgaon',
    address: 'Sohna Road, Sector 48, Gurgaon, Haryana 122018',
    website: 'https://sample-partners.example',
    publicEmail: 'reach@sample-partners.example',
    publicPhone: '+91-124-5550106',
    source: 'Public Chamber of Commerce (Demo)',
    sourceUrl: 'https://directory.example/sample-partners',
    websiteStatus: 'WEBSITE_EXISTS',
    leadStatus: 'REPLIED',
    opportunityScore: 82,
    opportunityReason: 'Firm partner replied requesting demo link showcasing automated tax filing appointment scheduler.',
    isDemoData: true,
    organizationId: DEMO_ORGANIZATION_ID,
    createdAt: new Date(Date.now() - 1000 * 60 * 60 * 24 * 10).toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: 'demo-lead-007',
    businessName: 'Demo Tax Consultancy Gurgaon',
    profession: 'Chartered Accountant',
    city: 'Gurgaon',
    address: 'MG Road, Near Metro Station, Gurgaon, Haryana 122002',
    website: 'https://demo-tax-gurgaon.example',
    publicEmail: 'hello@demo-tax-gurgaon.example',
    publicPhone: '+91-124-5550107',
    source: 'Public Listing (Demo)',
    sourceUrl: 'https://directory.example/demo-tax-gurgaon',
    websiteStatus: 'WEBSITE_EXISTS',
    leadStatus: 'INTERESTED',
    opportunityScore: 89,
    opportunityReason: 'Reviewed interactive demo site; requested detailed proposal for full migration and SEO setup.',
    isDemoData: true,
    organizationId: DEMO_ORGANIZATION_ID,
    createdAt: new Date(Date.now() - 1000 * 60 * 60 * 24 * 12).toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: 'demo-lead-008',
    businessName: 'Test Accounting & Advisory',
    profession: 'Chartered Accountant',
    city: 'Delhi NCR',
    address: 'Nehru Place Commercial Complex, New Delhi 110019',
    website: 'https://test-accounting.example',
    publicEmail: 'contact@test-accounting.example',
    publicPhone: '+91-11-5550108',
    source: 'Public Registry (Demo)',
    sourceUrl: 'https://directory.example/test-accounting',
    websiteStatus: 'WEBSITE_EXISTS',
    leadStatus: 'PROPOSAL',
    opportunityScore: 91,
    opportunityReason: 'Proposal delivered for \$3,500 redesign including multi-lingual support and client document portal.',
    isDemoData: true,
    organizationId: DEMO_ORGANIZATION_ID,
    createdAt: new Date(Date.now() - 1000 * 60 * 60 * 24 * 15).toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: 'demo-lead-009',
    businessName: 'Example CA Enterprise Group',
    profession: 'Chartered Accountant',
    city: 'Gurgaon',
    address: 'Cyber City Building 9B, Gurgaon, Haryana 122002',
    website: 'https://example-ca-enterprise.example',
    publicEmail: 'team@example-ca-enterprise.example',
    publicPhone: '+91-124-5550109',
    source: 'Direct Discovery (Demo)',
    sourceUrl: 'https://directory.example/example-ca-enterprise',
    websiteStatus: 'WEBSITE_EXISTS',
    leadStatus: 'CUSTOMER',
    opportunityScore: 65,
    opportunityReason: 'Successfully converted to retainer client for ongoing website maintenance and security auditing.',
    isDemoData: true,
    organizationId: DEMO_ORGANIZATION_ID,
    createdAt: new Date(Date.now() - 1000 * 60 * 60 * 24 * 30).toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: 'demo-lead-010',
    businessName: 'Demo CA Firm 10 (Suppressed)',
    profession: 'Chartered Accountant',
    city: 'Gurgaon',
    address: 'Sector 29 Market, Gurgaon, Haryana 122001',
    website: 'https://demo-ca-10.example',
    publicEmail: 'do-not-email@demo-ca-10.example',
    publicPhone: '+91-124-5550110',
    source: 'Public Listing (Demo)',
    sourceUrl: 'https://directory.example/demo-ca-10',
    websiteStatus: 'WEBSITE_EXISTS',
    leadStatus: 'DO_NOT_CONTACT',
    opportunityScore: 10,
    opportunityReason: 'Contact requested exclusion. Global suppression active across all channels.',
    isDemoData: true,
    organizationId: DEMO_ORGANIZATION_ID,
    createdAt: new Date(Date.now() - 1000 * 60 * 60 * 24 * 4).toISOString(),
    updatedAt: new Date().toISOString(),
    suppressionRecords: [
      {
        id: 'supp-demo-010-email',
        leadId: 'demo-lead-010',
        organizationId: DEMO_ORGANIZATION_ID,
        channel: 'EMAIL',
        reason: 'Explicit opt-out request received from partner.',
        createdAt: new Date().toISOString(),
        createdBy: 'demo-compliance-system',
      },
      {
        id: 'supp-demo-010-phone',
        leadId: 'demo-lead-010',
        organizationId: DEMO_ORGANIZATION_ID,
        channel: 'VOICE',
        reason: 'Explicit opt-out request received from partner.',
        createdAt: new Date().toISOString(),
        createdBy: 'demo-compliance-system',
      },
    ],
  },
  {
    id: 'demo-lead-011',
    businessName: 'Fictional Audit Specialists',
    profession: 'Chartered Accountant',
    city: 'Gurgaon',
    address: 'Golf Course Extension Road, Sector 65, Gurgaon, Haryana 122102',
    website: 'https://fictional-audit.example',
    publicEmail: 'audit@fictional-audit.example',
    publicPhone: '+91-124-5550111',
    source: 'Public CA Registry (Demo)',
    sourceUrl: 'https://directory.example/fictional-audit',
    websiteStatus: 'REQUIRES_REVIEW',
    leadStatus: 'NOT_INTERESTED',
    opportunityScore: 35,
    opportunityReason: 'Public record listing requires manual review before verification.',
    isDemoData: true,
    organizationId: DEMO_ORGANIZATION_ID,
    createdAt: new Date(Date.now() - 1000 * 60 * 60 * 24 * 9).toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: 'demo-lead-012',
    businessName: 'Mock Corporate Compliance CA',
    profession: 'Chartered Accountant',
    city: 'Delhi NCR',
    address: 'Janakpuri District Centre, New Delhi 110058',
    website: 'https://mock-compliance.example',
    publicEmail: 'info@mock-compliance.example',
    publicPhone: '+91-11-5550112',
    source: 'Public Registry (Demo)',
    sourceUrl: 'https://directory.example/mock-compliance',
    websiteStatus: 'UNKNOWN',
    leadStatus: 'RESEARCHING',
    opportunityScore: 72,
    opportunityReason: 'Automated scan incomplete; status unknown pending verification.',
    isDemoData: true,
    organizationId: DEMO_ORGANIZATION_ID,
    createdAt: new Date(Date.now() - 1000 * 60 * 60 * 3).toISOString(),
    updatedAt: new Date().toISOString(),
  },
];

export const INITIAL_DEMO_JOBS: JobData[] = [
  {
    id: 'job-demo-001',
    organizationId: DEMO_ORGANIZATION_ID,
    type: 'LEAD_DISCOVERY',
    status: 'COMPLETED',
    progress: 100,
    metadata: { query: 'Chartered Accountants', location: 'Gurgaon', count: 12 },
    createdAt: new Date(Date.now() - 1000 * 60 * 60 * 24).toISOString(),
    startedAt: new Date(Date.now() - 1000 * 60 * 60 * 24).toISOString(),
    completedAt: new Date(Date.now() - 1000 * 60 * 60 * 23).toISOString(),
  },
  {
    id: 'job-demo-002',
    organizationId: DEMO_ORGANIZATION_ID,
    type: 'WEBSITE_ANALYSIS',
    status: 'COMPLETED',
    leadId: 'demo-lead-001',
    progress: 100,
    metadata: { url: 'https://demo-ca-01.example', speedScore: 34 },
    createdAt: new Date(Date.now() - 1000 * 60 * 60 * 12).toISOString(),
    startedAt: new Date(Date.now() - 1000 * 60 * 60 * 12).toISOString(),
    completedAt: new Date(Date.now() - 1000 * 60 * 60 * 11).toISOString(),
  },
  {
    id: 'job-demo-003',
    organizationId: DEMO_ORGANIZATION_ID,
    type: 'DEMO_GENERATION',
    status: 'RUNNING',
    leadId: 'demo-lead-002',
    progress: 65,
    metadata: { template: 'ca-corporate-vault', theme: 'navy-gold' },
    createdAt: new Date(Date.now() - 1000 * 60 * 15).toISOString(),
    startedAt: new Date(Date.now() - 1000 * 60 * 15).toISOString(),
  },
];

export const INITIAL_DEMO_AUDIT_LOGS: AuditLogData[] = [
  {
    id: 'audit-demo-001',
    action: 'LEAD_CREATED',
    entity: 'Lead',
    entityId: 'demo-lead-001',
    actor: 'Admin User',
    organizationId: DEMO_ORGANIZATION_ID,
    details: { businessName: 'Demo CA Firm 01', isDemoData: true },
    createdAt: new Date(Date.now() - 1000 * 60 * 60 * 24 * 7).toISOString(),
  },
  {
    id: 'audit-demo-002',
    action: 'LEAD_STATUS_CHANGED',
    entity: 'Lead',
    entityId: 'demo-lead-001',
    actor: 'Admin User',
    organizationId: DEMO_ORGANIZATION_ID,
    details: { from: 'NEW', to: 'QUALIFIED' },
    createdAt: new Date(Date.now() - 1000 * 60 * 60 * 4).toISOString(),
  },
  {
    id: 'audit-demo-003',
    action: 'LEAD_MARKED_DO_NOT_CONTACT',
    entity: 'Lead',
    entityId: 'demo-lead-010',
    actor: 'Admin User',
    organizationId: DEMO_ORGANIZATION_ID,
    details: { channel: 'ALL', reason: 'Explicit opt-out request received' },
    createdAt: new Date(Date.now() - 1000 * 60 * 60 * 2).toISOString(),
  },
];
