'use client';

import React from 'react';
import { WebsiteContent, WebsiteTheme, WebsiteDesign, WebsiteSectionType, WebsiteLayout, WebsiteTemplate } from '@/types';
import { TemplateHero } from './template-heroes';
import { TemplateServices } from './template-services';
import { TemplateHeader } from './template-headers';
import { TemplateCta } from './template-ctas';
import { AboutSection } from './about-section';
import { WhyChooseUsSection } from './why-choose-us-section';
import { IndustriesSection } from './industries-section';
import { TestimonialsSection } from './testimonials-section';
import { FaqSection } from './faq-section';
import { ContactSection } from './contact-section';
import { LocationSection } from './location-section';
import { FooterSection } from './footer-section';
import { ProcessSection } from './process-section';
import { TrustSection } from './trust-section';
import { ExpertiseSection } from './expertise-section';

interface DemoRendererProps {
  content: WebsiteContent;
  theme?: WebsiteTheme;
  design?: WebsiteDesign;
}

const DEFAULT_SECTION_ORDER: WebsiteSectionType[] = [
  'HERO',
  'SERVICES',
  'ABOUT',
  'WHY_CHOOSE_US',
  'INDUSTRIES',
  'FAQ',
  'CONTACT',
  'LOCATION',
];

export const TEMPLATE_MAP: Record<string, WebsiteTemplate> = {
  EDITORIAL_FINANCE: 'EDITORIAL_FINANCE',
  MODERN_FINTECH: 'MODERN_FINTECH',
  LUXURY_PROFESSIONAL: 'LUXURY_PROFESSIONAL',
  SWISS_MINIMAL: 'SWISS_MINIMAL',
  MODERN_INDIAN: 'MODERN_INDIAN',
  MODERN_CORPORATE: 'MODERN_FINTECH',
  PREMIUM_PROFESSIONAL: 'LUXURY_PROFESSIONAL',
  TRADITIONAL_CA: 'SWISS_MINIMAL',
  CA_ACCOUNTING_PROFESSIONAL: 'MODERN_INDIAN',
};

export function DemoRenderer({ content, theme, design }: DemoRendererProps) {
  // Ensure content and theme are objects in case they were parsed from raw JSON
  const safeContent: WebsiteContent =
    typeof content === 'string' ? JSON.parse(content) : (content || {});

  const activeDesign: WebsiteDesign | undefined = design || safeContent.design;
  const rawTheme = theme || activeDesign?.theme || safeContent.theme;
  const activeTheme: WebsiteTheme =
    typeof rawTheme === 'string' ? JSON.parse(rawTheme) : rawTheme;

  const safeTheme: WebsiteTheme = {
    id: activeTheme?.id || 'executive-navy',
    name: activeTheme?.name || 'Executive Navy',
    primaryColor: activeTheme?.primaryColor || '#1e3a8a',
    secondaryColor: activeTheme?.secondaryColor || '#1e293b',
    accentColor: activeTheme?.accentColor || '#2563eb',
    fontFamily: activeTheme?.fontFamily || 'sans',
    style: activeTheme?.style || 'corporate',
    borderRadius: activeTheme?.borderRadius || 'md',
  };

  const rawLayout = activeDesign?.layout || safeContent.meta?.templateId || 'MODERN_INDIAN';
  const activeTemplate: WebsiteTemplate =
    activeDesign?.template ||
    TEMPLATE_MAP[rawLayout] ||
    (TEMPLATE_MAP[activeDesign?.layout || ''] as WebsiteTemplate) ||
    'MODERN_INDIAN';

  const layout: WebsiteLayout = activeTemplate;

  const rawOrder = activeDesign?.sectionOrder;
  const sectionOrder: WebsiteSectionType[] =
    Array.isArray(rawOrder) && rawOrder.length > 0
      ? rawOrder
      : DEFAULT_SECTION_ORDER;

  const brandData = safeContent.brand || {
    businessName: 'Chartered Accountants',
    tagline: 'Professional Chartered Accountancy & Tax Advisory',
    provenance: 'NEUTRAL_PLACEHOLDER' as const,
  };

  const navigationData = safeContent.navigation || {
    items: [
      { label: 'Home', href: '#hero' },
      { label: 'Services', href: '#services' },
      { label: 'About', href: '#about' },
      { label: 'Contact', href: '#contact' },
    ],
    ctaText: 'Schedule Consultation',
    ctaHref: '#contact',
  };

  const footerData = safeContent.footer || {
    copyright: `© ${new Date().getFullYear()} ${brandData.businessName}. All rights reserved.`,
    disclaimer: 'Personalized website demonstration concept generated by GetVisible. Prepared exclusively for evaluation.',
  };

  const renderSection = (sectionType: WebsiteSectionType) => {
    switch (sectionType) {
      case 'HERO':
        return safeContent.hero ? (
          <TemplateHero key="hero" hero={safeContent.hero} brand={brandData} theme={safeTheme} template={activeTemplate} />
        ) : null;
      case 'TRUST':
        return safeContent.trust ? (
          <TrustSection key="trust" trust={safeContent.trust} brand={brandData} theme={safeTheme} layout={layout} />
        ) : null;
      case 'SERVICES':
        return safeContent.services && safeContent.services.items?.length > 0 ? (
          <TemplateServices key="services" services={safeContent.services} theme={safeTheme} template={activeTemplate} />
        ) : null;
      case 'ABOUT':
        return safeContent.about ? (
          <AboutSection key="about" about={safeContent.about} theme={safeTheme} template={activeTemplate} />
        ) : null;
      case 'EXPERTISE':
        return safeContent.expertise ? (
          <ExpertiseSection key="expertise" expertise={safeContent.expertise} theme={safeTheme} layout={layout} />
        ) : null;
      case 'PROCESS':
        return safeContent.process ? (
          <ProcessSection key="process" process={safeContent.process} theme={safeTheme} layout={layout} />
        ) : null;
      case 'WHY_CHOOSE_US':
        return safeContent.whyChooseUs && safeContent.whyChooseUs.points?.length > 0 ? (
          <WhyChooseUsSection key="why-choose-us" whyChooseUs={safeContent.whyChooseUs} theme={safeTheme} />
        ) : null;
      case 'INDUSTRIES':
        return safeContent.industries && safeContent.industries.enabled !== false && safeContent.industries.items?.length > 0 ? (
          <IndustriesSection key="industries" industries={safeContent.industries} theme={safeTheme} />
        ) : null;
      case 'TESTIMONIALS':
        return safeContent.testimonials && safeContent.testimonials.enabled !== false && safeContent.testimonials.items?.length > 0 ? (
          <TestimonialsSection key="testimonials" testimonials={safeContent.testimonials} theme={safeTheme} />
        ) : null;
      case 'FAQ':
        return safeContent.faq && safeContent.faq.items?.length > 0 ? (
          <FaqSection key="faq" faq={safeContent.faq} theme={safeTheme} />
        ) : null;
      case 'CTA':
        return safeContent.ctaBanner ? (
          <TemplateCta key="cta" ctaBanner={safeContent.ctaBanner} brand={brandData} theme={safeTheme} template={activeTemplate} />
        ) : null;
      case 'CONTACT':
        return safeContent.contact ? (
          <ContactSection key="contact" contact={safeContent.contact} theme={safeTheme} />
        ) : null;
      case 'LOCATION':
        return safeContent.location ? (
          <LocationSection key="location" location={safeContent.location} brand={brandData} theme={safeTheme} />
        ) : null;
      default:
        return null;
    }
  };

  return (
    <div
      className={`min-h-screen bg-white dark:bg-slate-950 text-slate-900 dark:text-slate-100 selection:bg-blue-500/20 ${
        safeTheme.fontFamily === 'serif' ? 'font-serif' : 'font-sans'
      }`}
      style={
        {
          '--demo-primary': safeTheme.primaryColor,
          '--demo-secondary': safeTheme.secondaryColor,
          '--demo-accent': safeTheme.accentColor,
        } as React.CSSProperties
      }
    >
      {/* Template-Specific Navigation Header */}
      <TemplateHeader
        brand={brandData}
        navigation={navigationData}
        theme={safeTheme}
        template={activeTemplate}
      />

      {/* Main Sections Ordered Dynamically by Template Configuration */}
      <main>
        {sectionOrder.map((sectionType) => renderSection(sectionType))}
      </main>

      {/* Footer */}
      <FooterSection
        footer={footerData}
        brand={brandData}
        navigation={navigationData}
        theme={safeTheme}
      />
    </div>
  );
}

