import { WebsiteTheme } from '@/types';

// Predefined professional themes
export const THEMES: Record<string, WebsiteTheme> = {
  executiveNavy: {
    id: 'executive-navy',
    name: 'Executive Navy',
    primaryColor: '#1e3a8a',
    secondaryColor: '#1e293b',
    accentColor: '#2563eb',
    fontFamily: 'sans',
    style: 'corporate',
    borderRadius: 'md',
  },
  corporateSlate: {
    id: 'corporate-slate',
    name: 'Corporate Slate',
    primaryColor: '#0f172a',
    secondaryColor: '#334155',
    accentColor: '#0284c7',
    fontFamily: 'sans',
    style: 'corporate',
    borderRadius: 'md',
  },
  emeraldPrestige: {
    id: 'emerald-prestige',
    name: 'Emerald Prestige',
    primaryColor: '#064e3b',
    secondaryColor: '#134e4a',
    accentColor: '#059669',
    fontFamily: 'sans',
    style: 'corporate',
    borderRadius: 'sm',
  },
  classicBurgundy: {
    id: 'classic-burgundy',
    name: 'Classic Burgundy',
    primaryColor: '#4c0519',
    secondaryColor: '#27272a',
    accentColor: '#e11d48',
    fontFamily: 'serif',
    style: 'corporate',
    borderRadius: 'sm',
  },
  regalIndigo: {
    id: 'regal-indigo',
    name: 'Regal Indigo',
    primaryColor: '#312e81',
    secondaryColor: '#1e1b4b',
    accentColor: '#6366f1',
    fontFamily: 'sans',
    style: 'corporate',
    borderRadius: 'md',
  },
  industrialAmber: {
    id: 'industrial-amber',
    name: 'Industrial Amber',
    primaryColor: '#78350f',
    secondaryColor: '#292524',
    accentColor: '#d97706',
    fontFamily: 'sans',
    style: 'corporate',
    borderRadius: 'sm',
  },
  techTeal: {
    id: 'tech-teal',
    name: 'Tech Teal',
    primaryColor: '#0f766e',
    secondaryColor: '#042f2e',
    accentColor: '#14b8a6',
    fontFamily: 'sans',
    style: 'modern',
    borderRadius: 'md',
  },
  heritageBronze: {
    id: 'heritage-bronze',
    name: 'Heritage Bronze',
    primaryColor: '#451a03',
    secondaryColor: '#1c1917',
    accentColor: '#b45309',
    fontFamily: 'serif',
    style: 'corporate',
    borderRadius: 'sm',
  },
};
